apiVersion: v1
data:
  ip-watcher-cert.pfx: {{ required "A valid PFX certificate must be  provided in the certificate value" .Values.certificate }}
kind: Secret
metadata:
  name: {{ include "ip-watcher.fullname" . }}-certificate-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
