apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ip-watcher.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  IPWatcher_AzureStorageConfiguration__Authentication__AzureADClientID: {{ required "A valid Azure AD Client ID is required in the azure.auth.clientID value" .Values.azure.auth.clientID }}
  IPWatcher_AzureStorageConfiguration__Authentication__AzureADTenantID: {{ required "A valid Azure AD Tenant ID is required in the azure.auth.tenantID value" .Values.azure.auth.tenantID }} 
  IPWatcher_AzureStorageConfiguration__Authentication__X509Password: {{ required "A valid Certificate Password is required in the azure.auth.certPassword value" .Values.azure.auth.certPassword }} 
